CAR_MODELS = {
    'alfa': ['giulia', 'stelvio', 'giulietta', 'mito'],
    'audi': ['a1', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'q2', 'q3', 'q5', 'q7', 'q8', 'tt', 'r8', 's3', 's4', 's5', 's6', 's7', 's8', 'rs3', 'rs4', 'rs5', 'rs6', 'rs7', 'rsq3'],
    'bmw': ['1 series', '2 series', '3 series', '4 series', '5 series', '6 series', '7 series', '8 series', 'i3', 'i8', 'm2', 'm3', 'm4', 'm5', 'm6', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'z4'],
    'citroen': ['c1', 'c3', 'c4', 'c5', 'berlingo', 'cactus', 'ds3', 'ds4', 'ds5', 'grand c4 spacetourer'],
    'dacia': ['logan', 'sandero', 'duster', 'lodgy', 'dokker'],
    'fiat': ['500', '500x', '500l', 'panda', 'punto', 'tipo', '500c', '500l living', '500e'],
    'ford': ['fiesta', 'focus', 'mondeo', 'mustang', 'ka', 'kuga', 'ecosport', 'edge', 's-max', 'galaxy', 'ranger', 'transit'],
    'honda': ['civic', 'accord', 'cr-v', 'hr-v', 'jazz', 'nsx'],
    'hyundai': ['i10', 'i20', 'i30', 'i40', 'ioniq', 'kona', 'nexo', 'tucson', 'santa fe', 'ioniq electric'],
    'chevrolet': ['spark', 'aveo', 'cruze', 'malibu', 'camaro', 'corvette', 'trax', 'equinox', 'captiva', 'orlando', 'blazer', 'tahoe', 'suburban'],
    'kia': ['picanto', 'rio', 'ceed', 'optima', 'stinger', 'sportage', 'sorento', 'niro', 'soul', 'stonic'],
    'mercedes': ['a-class', 'b-class', 'c-class', 'e-class', 's-class', 'cla', 'cls', 'gla', 'glb', 'glc', 'gle', 'glc coupe', 'gle coupe', 'gls', 'slc', 'slk', 'sl', 'amg gt'],
    'mitsubishi': ['space star', 'asx', 'eclipse cross', 'outlander', 'pajero', 'l200'],
    'nissan': ['micra', 'leaf', 'note', 'juke', 'qashqai', 'x-trail', 'pulsar', 'pathfinder', '370z', 'gt-r', 'nv200'],
    'opel': ['corsa', 'astra', 'insignia', 'mokka', 'crossland x', 'grandland x', 'zafira', 'adam'],
    'peugeot': ['108', '208', '308', '508', '2008', '3008', '5008', 'partner', 'traveller', 'rifter', 'expert', 'boxer'],
    'renault': ['twingo', 'clio', 'captur', 'megane', 'scenic', 'kadjar', 'espace', 'talisman', 'koleos', 'zoe'],
    'seat': ['mii', 'ibiza', 'leon', 'toledo', 'arona', 'ateca', 'alhambra', 'tarraco'],
    'suzuki': ['ignis', 'swift', 'baleno', 'vitara', 'sx4 s-cross', 's-cross', 'jimny', 'celerio'],
    'skoda': ['citigo', 'fabia', 'scala', 'octavia', 'superb', 'kamiq', 'karoq', 'kodiaq', 'rapid', 'yeti'],
    'toyota': ['aygo', 'yaris', 'auris', 'corolla', 'prius', 'avensis', 'chr', 'rav4', 'highlander', 'land cruiser', 'hilux'],
    'volkswagen': ['up', 'polo', 'golf', 'passat', 'arteon', 't-roc', 'tiguan', 'touareg', 'touran', 'sharan', 'beetle', 'jetta', 'caddy', 'california', 'multivan', 'caravelle', 'amarok'],
    'volvo': ['v40', 'v60', 'v90', 's60', 's90', 'xc40', 'xc60', 'xc90', 'v70', 'xc70'],
    'mazda': ['2', '3', '6', 'cx-3', 'cx-4', 'cx-5', 'cx-8', 'cx-9', 'mx-5', 'cx-7', 'cx3', 'cx5', 'cx8', '323']
}