CAR_MODELS = {
    'alfa': [],
    'audi': [],
    'bmw': [], 
    'citroen': [], 
    'dacia': [],
    'fiat': [],
    'ford': [], 
    'honda': [],
    'hyundai': [], 
    'chevrolet': [], 
    'kia': [], 
    'mazda': ['2', '3', '6', 'cx-3', 'cx-4', 'cx-5', 'cx-8', 'cx-9', 'mx-5', 'cx-7'], 
    'mercedes': [], 
    'mitsubishi': [], 
    'nissan': [], 
    'opel': [], 
    'peugeot': [], 
    'renault': [], 
    'seat': [], 
    'suzuki': [], 
    'skoda': [], 
    'toyota': [], 
    'volkswagen': [],
    'volvo': [],
}